local defaults = {
    _meta = {
        schema_version = 1,
        files_per_page_defaulted = false,
    },
    localization = {
        default_locale = "en",
        locales = {
            "en",
            "it",
            "es",
            "fr",
            "nl",
            "pt_BR",
            "pt_PT",
            "ro",
            "ru",
            "zh_CN",
            "zh_TW",
        },
    },
    features = {
        navbar = true,
        quick_settings = true,
        zen_mode = true,
        status_bar = true,
        disable_top_menu_swipe_zones = true,
        browser_folder_cover = true,
        browser_hide_underline = true,
        browser_hide_up_folder = true,
        browser_cover_rounded_corners = false,
        reader_clock = true,
        reader_bottom_menu = false,
        night_mode_schedule = false,
        warmth_schedule     = false,
        brightness_schedule = false,
    },
    navbar = {
        show_tabs = {
            books = true,
            manga = false,
            news = false,
            continue = true,
            history = false,
            favorites = true,
            collections = false,
            exit = false,
            page_left = false,
            page_right = false,
            menu = false,
        },
        tab_order = { "page_left", "books", "manga", "news", "continue", "history", "favorites", "collections", "exit", "page_right", "menu" },
        show_labels = true,
        show_top_border = true,
        books_label = "Books",
        manga_action = "rakuyomi",
        manga_folder = "",
        news_action = "quickrss",
        news_folder = "",
        colored = false,
        active_tab_color = { 0x33, 0x99, 0xFF },
        show_in_standalone = true,
        show_top_gap = false,
        active_tab_styling = true,
        active_tab_bold = true,
        active_tab_underline = false,
        underline_above = true,
    },
    quick_settings = {
        button_order = { "wifi", "night", "rotate", "zen", "settings", "usb", "search", "quickrss", "cloud", "zlibrary", "calibre", "notion", "streak", "opds", "filebrowser", "restart", "exit", "sleep" },
        show_buttons = {
            wifi = true,
            night = true,
            rotate = true,
            zen = true,
            settings = true,
            usb = false,
            search = false,
            quickrss = false,
            cloud = false,
            zlibrary = false,
            calibre = false,
            restart = true,
            exit = false,
            sleep = true,
            notion = false,
            streak = false,
            opds = false,
            filebrowser = false,
        },
        show_frontlight = true,
        show_warmth = true,
        open_on_start = true,
    },
    status_bar = {
        show = {
            wifi = true,
            disk = false,
            ram = false,
            frontlight = false,
            battery = true,
        },
        custom_text = " ",
        separator_key = "small-space",
        custom_separator = "  ",
        order = { "wifi", "disk", "ram", "frontlight", "battery" },
        show_time = true,
        time_12h = true,
        show_bottom_border = false,
        colored = false,
        bold_text = false,
        hide_browser_bar = true,
    },
    browser_hide_up_folder = {
        hide_up_folder = true,
    },
    browser_cover_badges = {
        show_mosaic_progress = true,
    },
    browser_page_count = {
        show_page_count = false,
    },
    browser_preload_bookinfo = {
        preload_bookinfo = true,
    },
    context_menu = {
        allow_delete = false,
    },
    reader_clock = {
        use_24h = false,
        position = "center",
    },
    reader_footer = {
        verbose_chapter_time = false,
    },
    night_mode_schedule = {
        night_on_h  = 22,
        night_on_m  = 0,
        night_off_h = 7,
        night_off_m = 0,
    },
    warmth_schedule = {
        day_h       = 7,
        day_m       = 0,
        day_value   = 6,
        night_h     = 20,
        night_m     = 0,
        night_value = 20,
    },
    brightness_schedule = {
        day_h       = 7,
        day_m       = 0,
        day_value   = 20,
        night_h     = 20,
        night_m     = 0,
        night_value = 5,
    },
}

return defaults
