local defaults = {
    _meta = {
        schema_version = 1,
    },
    localization = {
        default_locale = "en",
        locales = {
            "en",
            "it",
            "es",
            "fr",
            "nl",
            "pt_BR",
            "pt_PT",
            "ro",
            "ru",
            "zh_CN",
            "zh_TW",
        },
    },
    features = {
        navbar = true,
        quick_settings = true,
        titlebar = true,
        hide_pagination = true,
        disable_top_menu_zones = true,
        browser_folder_cover = true,
        browser_hide_underline = true,
        browser_up_folder = true,
        reader_header_clock = true,
    },
    navbar = {
        show_tabs = {
            books = true,
            manga = true,
            news = true,
            continue = true,
            history = false,
            favorites = false,
            collections = false,
            exit = false,
            page_left = false,
            page_right = false,
        },
        tab_order = { "page_left", "books", "manga", "news", "continue", "history", "favorites", "collections", "exit", "page_right" },
        show_labels = true,
        show_top_border = true,
        books_label = "Books",
        manga_action = "rakuyomi",
        manga_folder = "",
        news_action = "quickrss",
        news_folder = "",
        colored = false,
        active_tab_color = { 0x33, 0x99, 0xFF },
        show_in_standalone = true,
        show_top_gap = false,
        active_tab_styling = true,
        active_tab_bold = true,
        active_tab_underline = true,
        underline_above = true,
    },
    quick_settings = {
        button_order = { "wifi", "night", "rotate", "settings", "usb", "home", "search", "quickrss", "cloud", "zlibrary", "calibre", "notion", "streak", "opds", "filebrowser", "browserbar", "restart", "exit", "sleep" },
        show_buttons = {
            wifi = true,
            night = true,
            rotate = true,
            settings = true,
            usb = false,
            search = false,
            quickrss = false,
            cloud = false,
            zlibrary = false,
            calibre = false,
            restart = true,
            exit = true,
            sleep = true,
            home = true,
            browserbar = false,
            notion = false,
            streak = false,
            opds = false,
            filebrowser = false,
        },
        show_frontlight = true,
        show_warmth = true,
        open_on_start = false,
    },
    titlebar = {
        show = {
            wifi = true,
            disk = true,
            ram = false,
            frontlight = false,
            battery = true,
        },
        device_name = "",
        separator_key = "dot",
        custom_separator = "  ",
        order = { "wifi", "disk", "ram", "frontlight", "battery" },
        show_time = true,
        time_12h = false,
        show_bottom_border = true,
        colored = false,
        bold_text = false,
        hide_topbar = false,
    },
    browser_up_folder = {
        hide_empty_folder = false,
        hide_up_folder = true,
    },
    zen = {
        context_menu_override = false,
        cover_style_controls = true,
        hide_koreader_ui_sections = false,
        updater_enabled = false,
    },
}

return defaults
