local defaults = {
    _meta = {
        schema_version = 1,
    },
    localization = {
        default_locale = "en",
        locales = {
            "en",
            "it",
            "es",
            "fr",
            "nl",
            "pt_BR",
            "pt_PT",
            "ro",
            "ru",
            "zh_CN",
            "zh_TW",
        },
    },
    features = {
        navbar = true,
        quick_settings = true,
        zen_mode = false,
        titlebar = true,
        zen_pagination_bar = true,
        disable_top_menu_swipe_zones = true,
        browser_folder_cover = true,
        browser_hide_underline = true,
        browser_hide_up_folder = true,
        reader_header_clock = true,
    },
    navbar = {
        show_tabs = {
            books = true,
            manga = false,
            news = false,
            continue = true,
            history = false,
            favorites = true,
            collections = false,
            exit = false,
            page_left = false,
            page_right = false,
        },
        tab_order = { "page_left", "books", "manga", "news", "continue", "history", "favorites", "collections", "exit", "page_right" },
        show_labels = true,
        show_top_border = true,
        books_label = "Books",
        manga_action = "rakuyomi",
        manga_folder = "",
        news_action = "quickrss",
        news_folder = "",
        colored = false,
        active_tab_color = { 0x33, 0x99, 0xFF },
        show_in_standalone = true,
        show_top_gap = false,
        active_tab_styling = true,
        active_tab_bold = true,
        active_tab_underline = false,
        underline_above = true,
    },
    quick_settings = {
        button_order = { "wifi", "night", "rotate", "settings", "usb", "search", "quickrss", "cloud", "zlibrary", "calibre", "notion", "streak", "opds", "filebrowser", "restart", "exit", "sleep" },
        show_buttons = {
            wifi = true,
            night = true,
            rotate = true,
            settings = true,
            usb = false,
            search = false,
            quickrss = false,
            cloud = false,
            zlibrary = false,
            calibre = false,
            restart = true,
            exit = false,
            sleep = true,
            notion = false,
            streak = false,
            opds = false,
            filebrowser = false,
        },
        show_frontlight = true,
        show_warmth = true,
        open_on_start = true,
    },
    titlebar = {
        show = {
            wifi = true,
            disk = false,
            ram = false,
            frontlight = false,
            battery = true,
        },
        device_name = " ",
        separator_key = "small-space",
        custom_separator = "  ",
        order = { "wifi", "disk", "ram", "frontlight", "battery" },
        show_time = true,
        time_12h = false,
        show_bottom_border = true,
        colored = false,
        bold_text = false,
    },
    browser_hide_up_folder = {
        hide_up_folder = true,
    },
    reader_header_clock = {
        use_24h = false,
    }
}

return defaults
